config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'pages#home'
  get :home, :about, controller: :pages
  get :index, controller: :events
  resources :events

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  belongs_to :event
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendees
  has_many :event_groupships
  has_many :groups, :through => :event_groupships
  has_one :location
  belongs_to :category
end

app/models/event_groupship.rb
class EventGroupship < ActiveRecord::Base
  belongs_to :event
  belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_many :event_groupships 
  has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :event
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @events = Event.all
  end

  def new 
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.save

    redirect_to events_url
  end
  
  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)

    redirect_to event_url(@event)
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    redirect_to events_url
  end


  private

  def event_params
    params.require(:event).permit(:name, :description)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!  
  def about 

  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def nav_li text, path
    active = request.path == path ? :active : nil
    content_tag :li, link_to(text,path), class: active
  end 
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
  <p class="text-center">Copyright ©2014 Rails101s
    <br>Design by <a href="http://sdlong.logdown.com" target=_new>sdlong</a>
  </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Rails 101</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
	<li><%=link_to 'Home', root_path%></li>
  	<li><%=link_to 'About', about_path%></li>
  	<li><%=link_to 'Events', index_path%></li>
      </ul>
    </div><!-- /.navbar-collapse -->    
  </div><!-- /.container-fluid -->
</nav>

app/views/events/destroy.html.erb
def destroy
  @event = Event.find(params[:id])
  @event.destroy

  redirect_to :action => :index
end

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :method=> :patch do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <li>
    <%= event.name %>
    <%= link_to "Show", event_path(event) %>
    <%= link_to 'Edit', edit_event_path(event) %>
    <%= button_to 'Delete', event_path(event), :method => :delete, :data => { :confirm => "Are you sure?" } %>
  </li>
<% end %>
</ul>

<%= link_to 'New Event', new_event_path %><br>
<%= link_to 'Home page', root_path %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
    <%= f.label :name, "Name" %>
    <%= f.text_field :name %>

    <%= f.label :description, "Description" %>
    <%= f.text_area :description %>

    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/admin.html.erb
<html>
  <head>
    <title>back-ground</title>
  </head>
  <body>
    <h1>back-ground</h1>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>P1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <%= render 'common/navbar' %>
  <% if current_user %>
    <%= link_to('登出', destroy_user_session_path, :method => :delete) %>| 
    <%= link_to('修改密碼', edit_registration_path(:user)) %>
  <% else %>
    <%= link_to('註冊', new_registration_path(:user)) %> |
    <%= link_to('登入', new_session_path(:user)) %>
  <% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= render 'common/navbar' %>
<%= yield %>
</div>
<%= render 'common/footer' %>
</body>
</html>

app/views/layouts/events.html.erb
<html>
  <head>
    <title>event</title>
  </head>
  <body>
    <h1>Events</h1>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/gallery.html.erb
<!--A Design by W3layouts
Author: W3layout
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
<title>Mining a Industrial Category Flat Bootstarp responsive Website Template | Gallery :: w3layouts</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="keywords" content="Mining Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template, 
Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- bootstarp-css -->
<link href="css/bootstrap.css" rel="stylesheet" type="text/css" media="all" />
<!--// bootstarp-css -->
<!-- css -->
<link rel="stylesheet" href="css/style.css" type="text/css" media="all" />
<link rel="stylesheet" href="css/lightbox.css">
<!--// css -->
<script src="js/jquery-1.11.1.min.js"></script>
<script src="js/modernizr.custom.js"></script>
</head>
<body>
	<!-- banner -->
	<div class="banner">
		<div class="banner-content">
			<div class="logo">
				<a href="index.html">Mining</a>
			</div>
			<div class="top-nav">
				<span class="menu">MENU</span>
				<ul class="nav1 cl-effect-15">
					<li><a href="index.html" data-hover="Home">Home</a></li>
					<li><a href="about.html" data-hover="About">About</a></li>
					<li><a href="services.html" data-hover="Services">Services</a></li>
					<li><a href="typography.html" data-hover="Typography">Typography</a></li>
					<li><a href="gallery.html" class="active">Gallery</a></li>
					<li><a href="contact.html" data-hover="Contact">Contact</a></li>
				</ul>
				<!-- script-for-menu -->
					<script>
						 $( "span.menu" ).click(function() {
						$( "ul.nav1" ).slideToggle( 300, function() {
						// Animation complete.
							});
							});
					</script>
				<!-- /script-for-menu -->
			</div>
		</div>
	</div>
	<!-- //banner -->
	<!-- gallery -->
	<div class="gallery-top">
		<!-- container -->
		<div class="container">
			<div class="gallery-info">
				<h3>Gallery</h3>
			</div>
			<div class="gallery-grids-top">
				<div class="gallery-grids">
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g1.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g1.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g2.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g2.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g3.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g3.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g4.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g4.jpg" alt=""/></a>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="gallery-grids gallery-grids-middle">
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g5.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g5.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g6.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g6.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g1.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g1.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g2.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g2.jpg" alt=""/></a>
					</div>
					<div class="clearfix"> </div>
				</div>
				<div class="gallery-grids">
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g3.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g3.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g4.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g4.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g5.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g5.jpg" alt=""/></a>
					</div>
					<div class="col-md-3 gallery-grid">
						<a class="example-image-link" href="images/g6.jpg" data-lightbox="example-set" data-title=""><img class="example-image" src="images/g6.jpg" alt=""/></a>
					</div>
					<div class="clearfix"> </div>
				</div>
				<script src="js/lightbox-plus-jquery.min.js"></script>
			</div>
		</div>
		<!-- //container -->
	</div>
	<!-- //gallery -->
	<!-- footer -->
	<div class="footer">
		<!-- container -->
		<div class="container">
			<div class="footer-info">
				<h3>Contact</h3>
				<p class="f-address">09-45 Mary Road , London , J-9 09SD</p>
				<ul>
					<li><a href="#" class="facebook"> </a>
					<li><a href="#" class="facebook twitter"> </a>
					<li><a href="#" class="facebook chrome"> </a>
					<li><a href="#" class="facebook dribbble"> </a>
					<li><a href="#" class="facebook pinterest"> </a>
				</ul>
				<p class="copyright"> © 2015 Mining. All rights reserved | Design by <a href="http://w3layouts.com/">W3layouts</a></p>
			</div>	
		</div>
		<!-- //container -->
	</div>
	<!-- //footer -->
</body>	
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_navbar.html.erb
<style type='text/css'>
.row {
  list-style:inside;
}
.row LI.first {
  float: left;
  margin: 0px 10px 0px 10px;
}
</style>
<ul class=row>
  <li class=first>
    <%=link_to 'Home', root_path%>
  </li>
  <li class=first>
    <%=link_to 'About', about_path%>
  </li>
  <li class=first>
    <%=link_to 'Events', index_path%>
  </li>
</ul>